### ISSUE TITLE
Serious problem with array index accessing

### ISSUE THREAD

**Issue by muras** [jknack/handlebars.java#177]
Hi,

I have found weird thing with accessing arrays via index.
Please read details below.

``` java
// model classes
public class Model1 {
    private List<String> listOfValues1 = new ArrayList();
    public List<String> getListOfValues1() {
        return listOfValues1;
    }
    public void setListOfValues1(List<String> listOfValues1) {
        this.listOfValues1 = listOfValues1;
    }   
}
public class User {
    private String name;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name;
    }
    @Override
    public String toString() {
        return name;
    }
}
public class Model2 {
    private List<User> users = new ArrayList();
    public List<User> getUsers() {
        return users;
    }
    public void setUsers(List<User> users) {
        this.users = users;
    }
}

// model map
Map<String, Object> modelMap = new HashMap();

// model1
Model1 model1 = new Model1();
List<String> listOfValues1 = new ArrayList();
listOfValues1.add("m1-1");
listOfValues1.add("m1-2");
listOfValues1.add("m1-3");
model1.setListOfValues1(listOfValues1);
modelMap.put("model1", model1);

// model2
Model2 model2 = new Model2();
List<User> users = new ArrayList();
User u1 = new User();
u1.setName("User 1");
users.add(u1);
User u2 = new User();
u2.setName("User 2");
users.add(u2);
model2.setUsers(users);
modelMap.put("model2", model2);

// model3
modelMap.put("model3", true);
...
```
- Test 1 (ok)

``` handlebars
{{model1.listOfValues1.[0]}}
```

renders to:

``` html
m1-1
```
- Test 2 (ok)

``` handlebars
{{model1.listOfValues1.[0]}}
{{model2.users.[0]}}
```

renders to:

``` html
m1-1
User 1
```
- Test 3 (not ok)

``` handlebars
{{model1.listOfValues1.[0]}}
{{model2.users.[0].name}}
```

renders to empty string:

``` html
```
- Test 4 (not ok)

``` handlebars
{{model1.listOfValues1.[0]}}
{{#if model3}}
{{model2.users.[0].name}}
{{/if}}
```

throws exception:

``` java
Exception in thread "main" com.github.jknack.handlebars.HandlebarsException: test.html:4:1: found: '{{/', expected: '<EOF>'
{{/if}}
 ^
    at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:91)
    at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:57)
    at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:367)
    at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportInputMismatch(HbsErrorStrategy.java:185)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:107)
    at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:108)
    at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:89)
    at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:49)
    at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:438)
    at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:381)
    at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:367)
    at Main.main(Main.java:73)
```
- Test 5 (ok)

``` handlebars
{{model1.listOfValues1.[0]}}
{{#if model3}}
{{model2.users.[0]}}
{{/if}}
```

renders to:

``` html
m1-1

User 1
```

Please help.

**Comment by dontgitit** [comment]
Hi, 

I'm finding a similar issue in 2.0.0 with test case 4; but only if everything is **on one line**, i.e.

```
{{model1.listOfValues1.[0]}} {{#if model3}} {{model2.users.[0].name}} {{/if}}
```

Results in:
```
[info]   com.github.jknack.handlebars.HandlebarsException: inline@62cc4226:1:70: found: '{{/', expected: '<EOF>'
[info] {{model1.listOfValues1.[0]}} {{#if model3}} {{model2.users.[0].name}} {{/if}}
[info]                                                                       ^
[info]   at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
[info]   at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:67)
[info]   at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:561)
[info]   at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportInputMismatch(HbsErrorStrategy.java:185)
[info]   at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:150)
[info]   at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:114)
[info]   at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:84)
[info]   at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:49)
[info]   at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:435)
[info]   at com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:405)
[info]   ...
```

Omitting different parts, it compiles without exception (not sure if it prints the right thing though when actually applied); examples that compile without exception:
```
{{#if model3}} {{model2.users.[0].name}} {{/if}}
```
```
{{model1.listOfValues1.[0]}} {{#if model3}} {{model2.users.[0]}} {{/if}}
```
