### ISSUE TITLE
Nested Helpers implemented in JS are throwing exceptions

### ISSUE THREAD

**Issue by PedroBorracho** [jknack/handlebars.java#407]
I have defined 2 helpers (compare and uppercase) in JS and both when used alone are working as expected:

```javascript
{{#compare true true}}
    ok
{{else}}
    ko
{{/compare}}
```
```javascript
{{uppercase "aaa"}}
```
But I have NPE exceptions when I do:
```javascript
{{#compare true true}}
    {{uppercase "aaa"}}
{{else}}
    {{uppercase "bbb"}}
{{/compare}}
```
Caused by: com.github.jknack.handlebars.HandlebarsException: inline@1954102c:2:6: java.lang.NullPointerException
    inline@1954102c:2:6
	at java.util.AbstractCollection.addAll(AbstractCollection.java:341)
	at com.github.jknack.handlebars.Context$CompositeValueResolver.propertySet(Context.java:129)
	at com.github.jknack.handlebars.Context.propertySet(Context.java:427)
	at com.github.jknack.handlebars.Context.propertySet(Context.java:436)
	at com.github.jknack.handlebars.internal.js.RhinoHandlebars.toJsObject(RhinoHandlebars.java:370)
	at com.github.jknack.handlebars.internal.js.RhinoHandlebars.access$200(RhinoHandlebars.java:44)
	at com.github.jknack.handlebars.internal.js.RhinoHandlebars$1.apply(RhinoHandlebars.java:232)
	at com.github.jknack.handlebars.internal.Variable.merge(Variable.java:153)

You can see below the code of the 2 helpers, implemented and loaded from a JS file: do you have any advice on the reason why the inner helper is failing? I thinks the issue is on how the context is passed to the inner helper, because it works fine if I change the inner helper with the built-in {{#if}}.

```javascript
Handlebars.registerHelper('compare', function(lvalue, rvalue, options) {
    ...
    var result = ...

    if( result ) {
        return options.fn(this);
    } else {
        return options.inverse(this);
    }
});

Handlebars.registerHelper('uppercase', function(str, options) {
    if (arguments.length < 2 || str === null){
        return '';
    }
    if(str.toUpperCase){
        return str.toUpperCase();
    }
    return str;
});
```

Thanks!

**Comment by PedroBorracho** [comment]
An other case of fail is:
```javascript
{{#compare true true}}
    {{#compare true true}}
        kkk
    {{/compare}}
{{/compare}}
```

**Comment by jknack** [comment]
Can't reproduce it
