### ISSUE TITLE
HbsErrorReporter

### ISSUE THREAD

**Issue by gitNas** [jknack/handlebars.java#452]
Hi,

 I had this exception when i wanted to use handlebars.

com.github.jknack.handlebars.HandlebarsException: inline@54609f21:1:60: found: '{{', expected: '<EOF>'
{{Rh4nDqGfAkSwnvt1BoUDUQ}}  {{2aRpN6hJKk-9EGWgLZNAzw}} {{JvaH_W34vkW2ahccaU_7gA}}, 
                                                            ^
    at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
    at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
    at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:558)
    at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportInputMismatch(HbsErrorStrategy.java:186)
    at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:150)
    at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:167)
    at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:84)
    at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:49)
    at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:442)
    at com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:412)
    at com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:396)
    at com.sarbacane.routing.templater.CachedTemplates.<init>(CachedTemplates.java:84)
    at com.sarbacane.routing.templater.CachedTemplates.from(CachedTemplates.java:89)
    at com.sarbacane.routing.templater.RoutingTemplater.template(RoutingTemplater.java:179)
    at com.sarbacane.routing.templater.MessageTemplaterTest.testTemplateCustomUnsubscribeList(MessageTemplaterTest.java:158)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by jknack** [comment]
Please add a reproducible example that includes template+data.

Thanks

**Comment by gitNas** [comment]
private static final Handlebars HANDLEBARS = new Handlebars();

	@Test
	public void test() throws IOException {
		String example = "Dear Mr {{recipient.firstname}} {{Rh4nDqGfAkSwnvt1BoUDUQ}}  {{2aRpN6hJKk-9EGWgLZNAzw}} {{JvaH_W34vkW2ahccaU_7gA}}, \n\nb";
		Template result = HANDLEBARS.compileInline(example);
	}

**Comment by jknack** [comment]
Thanks.

This is an invalid identifier: ```2aRpN6hJKk-9EGWgLZNAzw``` a var or place holder can't start with a ```number```, but can be escaped it with ```[...]``` like:

```
Dear Mr {{recipient.firstname}} {{Rh4nDqGfAkSwnvt1BoUDUQ}}  {{[2aRpN6hJKk-9EGWgLZNAzw]}} {{JvaH_W34vkW2ahccaU_7gA}}, \n\nb
```

I will try to improve error reporting, so let's keep this open.
