### ISSUE TITLE
Can I use enableFallback in Spring framework?

### ISSUE THREAD

**Issue by jinmabus** [jknack/handlebars.java#497]
I use handlebars-springmvc in my Spring framework + Spring mobile app.

I want to use "enableFallback" feature. But it does not work.

I tested Freemarker. And It works good. But I can't do with handlebars-springmvc.

Handlebars-springmvc always return 500 error code although enableFallback is true.

```
http://localhost:8080/webtest/ -> 200 code
http://localhost:8080/webtest/m -> 200 code
http://localhost:8080/webtest/hello -> 200 code 
   template path: /WEB-INF/templates/hello.html
http://localhost:8080/webtest/m/hello -> 500 code!!
   Error : "FileNotFoundException : /WEB-INF/templates/m/hello.html"
   I want to show /WEB-INF/templates/hello.html template file. Because /WEB-INF/templates/m/hello.html is not exists.
```

- dispatch-servlet.xml
```
<beans xmlns="http://www.springframework.org/schema/beans"
        xmlns:context="http://www.springframework.org/schema/context"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tx="http://www.springframework.org/schema/tx"
        xmlns:mvc="http://www.springframework.org/schema/mvc"
        xsi:schemaLocation="
http://www.springframework.org/schema/beans
http://www.springframework.org/schema/beans/spring-beans.xsd
http://www.springframework.org/schema/context
http://www.springframework.org/schema/context/spring-context.xsd
http://www.springframework.org/schema/tx
http://www.springframework.org/schema/tx/spring-tx.xsd
http://www.springframework.org/schema/mvc
http://www.springframework.org/schema/mvc/spring-mvc-4.2.xsd">

        <context:component-scan base-package="me.kjjo.webtest" />
        <mvc:annotation-driven>
                <mvc:argument-resolvers>
                        <bean class="org.springframework.mobile.device.site.SitePreferenceWebArgumentResolver" />
                        <bean class="org.springframework.mobile.device.DeviceWebArgumentResolver" />
                </mvc:argument-resolvers>
        </mvc:annotation-driven>

        <mvc:interceptors>
                <!-- Resolve the device which has generated the request -->
                <bean class="org.springframework.mobile.device.DeviceResolverHandlerInterceptor" />

                <!-- User's site preference -->
                <bean class="org.springframework.mobile.device.site.SitePreferenceHandlerInterceptor" />

                <!-- Redirects users to the device specific site -->
                <bean class="org.springframework.mobile.device.switcher.SiteSwitcherHandlerInterceptor" factory-method="urlPath">
                        <constructor-arg value="/m" />
                        <constructor-arg value="/t" />
                        <constructor-arg value="/webtest" />
                </bean>
        </mvc:interceptors>

        <!-- Device aware view resolving -->
        <bean id="liteDeviceDelegatingViewResolver" class="org.springframework.mobile.device.view.LiteDeviceDelegatingViewResolver">
                <constructor-arg>
                        <bean id="viewResolver"
                                class="com.github.jknack.handlebars.springmvc.HandlebarsViewResolver">
                                <property name="prefix" value="/WEB-INF/templates/" />
                                <property name="suffix" value=".html" />
                                <property name="cache" value="false" />
                        </bean>
                </constructor-arg>

                <property name="mobilePrefix" value="m/" />
                <property name="tabletPrefix" value="t/" />
                <property name="enableFallback" value="true" />
        </bean>

</beans>
```

- Controller class
```
@Controller
public class WebController {
	private final Log logger = LogFactory.getLog(WebController.class);
	
	@RequestMapping("/")
	public String index(Model model, Device device) {
		logger.info("device isNormal:"+device.isNormal());
		logger.info("device isTablet:"+device.isTablet());
		logger.info("device isMobile:"+device.isMobile());
		
		return "index";
	}
	@RequestMapping("/hello")
	public String hello(Model model, Device device) {
		return "hello";
	}
}
```

- Directory structure
```
- WEB-INF/templates
- WEB-INF/templates/index.html
- WEB-INF/templates/m/index.html
- WEB-INF/templates/hello.html
```

- Stack trace:
```
3월 22, 2016 4:07:51 오후 org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcher] in context with path [/webtest] threw exception
java.io.FileNotFoundException : /WEB-INF/templates/m/hello.html
     at com.github.jknack.handlebars.io.URLTemplateLoader.sourceAt(URLTemplateLoader.java:70)
     at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:357)
     at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:343)
     at com.github.jknack.handlebars.springmvc.HandlebarsViewResolver.configure(HandlebarsViewResolver.java:195)
     at com.github.jknack.handlebars.springmvc.HandlebarsViewResolver.buildView(HandlebarsViewResolver.java:177)
     at org.springframework.web.servlet.view.UrlBasedViewResolver.loadView(UrlBasedViewResolver.java:481)
     at org.springframework.web.servlet.view.AbstractCachingViewResolver.createView(AbstractCachingViewResolver.java:244)
     at org.springframework.web.servlet.view.UrlBasedViewResolver.createView(UrlBasedViewResolver.java:446)
     at org.springframework.web.servlet.view.AbstractCachingViewResolver.resolveViewName(AbstractCachingViewResolver.java:146)
     at org.springframework.mobile.device.view.AbstractDeviceDelegatingViewResolver.resolveViewName(AbstractDeviceDelegatingViewResolver.java:111)
     at org.springframework.web.servlet.DispatcherServlet.resolveViewName(DispatcherServlet.java:1282)
     at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1223)
     at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1027)
     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:971)
     at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893)
...
```

- Environment:
```
handlebars-springmvc 4.0.5
Jdk 1.7
tomcat 7
Spring 3.1.1.RELEASE
Spring mobile 1.1.5.RELEASE
```

- github source code:
https://github.com/jinmabus/handlebars-mobile-test

Thank you.

**Comment by jknack** [comment]
Hi,

 I'm not aware of ```org.springframework.mobile.device.view.LiteDeviceDelegatingViewResolver``` and what does ```enableFallback``` but in ```HandlebarsViewResolver``` you need to set ```setFailOnMissingFile(false)```

```xml
<!-- Device aware view resolving -->
        <bean id="liteDeviceDelegatingViewResolver" class="org.springframework.mobile.device.view.LiteDeviceDelegatingViewResolver">
                <constructor-arg>
                        <bean id="viewResolver"
                                class="com.github.jknack.handlebars.springmvc.HandlebarsViewResolver">
                                <property name="prefix" value="/WEB-INF/templates/" />
                                <property name="suffix" value=".html" />
                                <property name="cache" value="false" />
                                <property name="failOnMissingFile" value="false" />
                        </bean>
                </constructor-arg>

                <property name="mobilePrefix" value="m/" />
                <property name="tabletPrefix" value="t/" />
                <property name="enableFallback" value="true" />
        </bean>
```

**Comment by jinmabus** [comment]
@jknack Thank you for your help. I solved it with your solution!

**Comment by jknack** [comment]
you're welcome and I invite you to try: http://jooby.org
