### ISSUE TITLE
raw-helper inside conditional results in Exception

### ISSUE THREAD

**Issue by lagrz** [jknack/handlebars.java#519]
When using the [raw-helper](http://handlebarsjs.com/block_helpers.html#raw-blocks) in java inside of a conditional statement results in an exception. The raw helper works fine when not nested in any form of conditional. Same template works flawless in the javascript version of handlebars. Used the maven versions `4.0.1 - 4.0.5` had same results.

```java
handlebars.registerHelper("raw-helper", (context, options) -> options.fn());
```

```hbs
{{#unless test}}
    {{{{raw-helper}}}}
        {{testing}}
    {{{{/raw-helper}}}}
{{/unless}}
```

```
com.github.jknack.handlebars.HandlebarsException: inline@1be01261:1:75: found: '<EOF>', expected: '{{/'
{{#unless test}}{{{{raw-helper}}}}{{testing}}{{{{/raw-helper}}}}{{/unless}}
                                                                           ^
	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:566)
	at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportInputMismatch(HbsErrorStrategy.java:186)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:148)
	at com.github.jknack.handlebars.internal.HbsParser.block(HbsParser.java:705)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:338)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:165)
	at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:84)
	at com.github.jknack.handlebars.cache.HighConcurrencyTemplateCache$1.call(HighConcurrencyTemplateCache.java:168)
	at com.github.jknack.handlebars.cache.HighConcurrencyTemplateCache$1.call(HighConcurrencyTemplateCache.java:165)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.github.jknack.handlebars.cache.HighConcurrencyTemplateCache.putIfAbsent(HighConcurrencyTemplateCache.java:185)
	at com.github.jknack.handlebars.cache.HighConcurrencyTemplateCache.cacheGet(HighConcurrencyTemplateCache.java:126)
	at com.github.jknack.handlebars.cache.HighConcurrencyTemplateCache.get(HighConcurrencyTemplateCache.java:96)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:414)
	at com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:384)
	at com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:368)
```

**Comment by jknack** [comment]
Fixed in master. will ```4.0.6``` release later today.

Also, I invite you to try: http://jooby.org

**Comment by homeation** [comment]
@jknack when is 4.0.6 expected to be released?

**Comment by jknack** [comment]
just released it, will be in central in 1 or 2 hours.

thanks
