### ISSUE TITLE
MethodValueResolver calling unrelated methods when used with JS helper

### ISSUE THREAD

**Issue by mohamnag** [jknack/handlebars.java#532]
I just hit a strange situation where the MethodValueResolver is just calling any method on the context when used together with a JavaScript helper loaded from a file. I made this basic sample [here](https://github.com/mohamnag/hbs_js_helper) that shows the problem.

When running this sample I get following exception:
```
Exception in thread "main" com.github.jknack.handlebars.HandlebarsException: ./src/main/resources/template.hbs:1:2: java.lang.RuntimeException: Why did you call me?
    ./src/main/resources/template.hbs:1:2
	at Model.badProperty(Model.java:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.github.jknack.handlebars.context.MethodValueResolver.invokeMember(MethodValueResolver.java:56)
	at com.github.jknack.handlebars.context.MethodValueResolver.invokeMember(MethodValueResolver.java:35)
	at com.github.jknack.handlebars.context.MemberValueResolver.resolve(MemberValueResolver.java:59)
	at com.github.jknack.handlebars.context.MemberValueResolver.propertySet(MemberValueResolver.java:169)
	at com.github.jknack.handlebars.Context$CompositeValueResolver.propertySet(Context.java:223)
	at com.github.jknack.handlebars.Context.propertySet(Context.java:554)
	at com.github.jknack.handlebars.Context.propertySet(Context.java:563)
	at com.github.jknack.handlebars.internal.js.RhinoHandlebars.toJsObject(RhinoHandlebars.java:410)
	at com.github.jknack.handlebars.internal.js.RhinoHandlebars.toJsObject(RhinoHandlebars.java:399)
	at com.github.jknack.handlebars.internal.js.RhinoHandlebars.access$000(RhinoHandlebars.java:44)
	at com.github.jknack.handlebars.internal.js.RhinoHandlebars$1.apply(RhinoHandlebars.java:269)
	at com.github.jknack.handlebars.internal.Variable.merge(Variable.java:166)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:128)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:94)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:128)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:116)
	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:100)
	at App.main(App.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.RuntimeException: Why did you call me?
	... 28 more
```

This should not happen because nowhere in my template I'm referring this property. This actually does not happen as long as I don't use JS helpers, even if Java helpers are present. I have a model that can not be changed due to backward compatibility and some of its methods are not meant to be checked unless some conditions are met.

Can this be fixed easily?

**Comment by jknack** [comment]
We need to convert `Model` to a `JS Object` that is the reason. Such conversion is done via: `ValueResolver.propertySet(Object)` (we use this to iterate over object in the for each helper)

An easy workaround will be to create a new `MethodValueResolver`, overrides the `propertySet` and catch and ignores any exception.

Follow me? It is hacky but I can't think in any other `easy` solution

**Comment by mohamnag** [comment]
Seems feasible at least. I will take a look at it later.

But this means in general using a JS handler is a bad idea because some of the methods are very heavy processes on my model that are not to be called.

**Comment by jknack** [comment]
yea kind of.. it depends on your data and types.. but yea we can say is more heavy than just Java.

**Comment by mohamnag** [comment]
Ok I did the same thing as you said and it was actually very easy to fix, thanks again and I'm closing the issue.
