### ISSUE TITLE
SecurityException in MemberValueResolver on AppEngine

### ISSUE THREAD

**Issue by atomicleopard** [jknack/handlebars.java#545]
AppEngine is a constrained environment where some java calls are not permitted. In particular, it seems to dislike reflection access to a package protected transient volatile attribute on AbstractMap. This is happening when I use a map as the data behind my template.

```
java.lang.SecurityException: java.lang.IllegalAccessException: Reflection is not allowed on transient volatile java.util.Set java.util.AbstractMap.keySet
    /static/email/welcome-email.hbs:4:3
	at com.google.appengine.runtime.Request.process-1211ebe0a290ef6b(Request.java)
	at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:42)
	at com.github.jknack.handlebars.context.MemberValueResolver.cache(MemberValueResolver.java:82)
```

MemberValueResolver doesn't seem to give any opportunity to control the caching behaviour, and which fields can or can't be cached. It seems to only use `instanceof AccessibleObject`.
It makes sense to me to check with the security manager to make sure that any given field can be made accessible, or to catch and swallow a SecurityException.

**Comment by jknack** [comment]
Silly AppEngine, but let's start to describing what are you trying to do? For example, don't see why `MemberValueResolver` is processing `AbstractMap`, it shouldn't. Did you apply/set custom value resolver?

Thanks.

**Comment by atomicleopard** [comment]
I'll provide some more info here, but in short I feel the correct fix would be to skip the cache on any fields that would fail with securityexception - it is documented API behaviour of setAccessible. But I agree, silly appengine ;)


Relevant stacktrace:
`Caused by: com.github.jknack.handlebars.HandlebarsException: /static/email/stylist-property-details.hbs:4:3: java.lang.SecurityException: java.lang.IllegalAccessException: Reflection is not allowed on transient volatile java.util.Set java.util.AbstractMap.keySet
    /static/email/template.hbs:4:3
	at com.google.appengine.runtime.Request.process-dde9fc41dd5c1a8c(Request.java)
	at java.lang.reflect.AccessibleObject.setAccessible(AccessibleObject.java:42)
	at com.github.jknack.handlebars.context.MemberValueResolver.cache(MemberValueResolver.java:82)
	at com.github.jknack.handlebars.context.MemberValueResolver.resolve(MemberValueResolver.java:54)
	at com.github.jknack.handlebars.Context$CompositeValueResolver.resolve(Context.java:197)
	at com.github.jknack.handlebars.internal.path.PropertyPath.eval(PropertyPath.java:52)
	at com.github.jknack.handlebars.Context$PathExpressionChain.next(Context.java:351)
	at com.github.jknack.handlebars.Context$PathExpressionChain.eval(Context.java:371)
	at com.github.jknack.handlebars.Context.get(Context.java:603)
	at com.github.jknack.handlebars.Context$PartialCtx.get(Context.java:163)
	at com.github.jknack.handlebars.internal.Variable.value(Variable.java:183)
	at com.github.jknack.handlebars.internal.Variable.merge(Variable.java:160)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:175)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:86)
	at com.github.jknack.handlebars.internal.Partial.merge(Partial.java:175)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.TemplateList.merge(TemplateList.java:95)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:130)
	at com.github.jknack.handlebars.internal.BaseTemplate.apply(BaseTemplate.java:118)
	at com.github.jknack.handlebars.internal.ForwardingTemplate.apply(ForwardingTemplate.java:100)
	at com.threewks.thundr.view.handlebars.HandlebarsViewResolver.resolve(HandlebarsViewResolver.java:74)
	at com.threewks.thundr.view.handlebars.HandlebarsViewResolver.resolve(HandlebarsViewResolver.java:1)
	at com.threewks.thundr.view.ViewResolverRegistry.resolve(ViewResolverRegistry.java:103)
	at com.threewks.thundr.mail.BaseMailer.render(BaseMailer.java:67)
	... 43 more
Caused by: java.lang.SecurityException: java.lang.IllegalAccessException: Reflection is not allowed on transient volatile java.util.Set java.util.AbstractMap.keySet
	... 73 more
Caused by: java.lang.IllegalAccessException: Reflection is not allowed on transient volatile java.util.Set java.util.AbstractMap.keySet`

Part of the failing template:
```


{{#*inline "title" }}
{{ title }}
{{/inline}}


```
Note that `{{ title }}` is line 4. This template uses template inheritence, not sure if that is related or not.

My template rendering code looks like this:

	
			Context context = Context.newBuilder(model).resolver(
						MapValueResolver.INSTANCE, 
						JavaBeanValueResolver.INSTANCE, 
						FieldValueResolver.INSTANCE, 
						MapValueResolver.INSTANCE, 
						MethodValueResolver.INSTANCE)
					.build();

			String content = template.apply(context);


Where `model` is a LinkedHashMap. Pretty much every Map available extends AbstractMap, which is where the issue lies.

One of the other things this brought to light for me is that potentially there's a lot of duplicate caching going on within a single context. Perhaps the cache could live on the context itself (which would incidentally permit better control over what is cached, when and how). I haven't dug too much through this behaviour though, so that's just a thought.

**Comment by atomicleopard** [comment]
Ok, it looks like between 4.0.0 and 4.0.3 this class changed from caching members as they were first requested to aggressively caching all members, which in this case means that fields that are never access by the template has .setAccessible() set on them (which can cause a SecurityException).

This seems like in most cases it would be very extraneous (i.e. the overhead of making accessible and caching all members of a type up the inheritance hierarchy) would probably outway the benefit of caching the members for access while the template is being run. In my example, my data model is always a map, but the data in the map could be a field, member, a bean or another map.

Rolling back to 4.0.0 works ok deployed, but i'd love to help resolve this for your great library.

**Comment by jknack** [comment]
Odd and don't remember a change there.

Anyway... your help and pull request will be highly appreciated.

Thanks and invite you to try: http://jooby.org
