### ISSUE TITLE
Block parameters break dumping the context

### ISSUE THREAD

**Issue by dontgitit** [jknack/handlebars.java#567]
Hi, dumping the full context via `{{{.}}}` seems to be broken if you try to do it inside a context that uses block parameters.

Sample data:
`{ "foo": ["a", "b", "c"] }`

Sample template (works):
```
{{#each foo}}
  context is {{{.}}}
{{/each}}
```

Sample output (works):
`context is a context is b context is c`

Sample template (doesn't work):
```
{{#each foo as |v k|}}
  context is {{{.}}}
{{/each}}
```

Throws:
```
com.github.jknack.handlebars.HandlebarsException: inline@56d1339c:2:16: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
    inline@56d1339c:2:16
	at java.util.ArrayList$SubList.rangeCheck(ArrayList.java:1217) ~[na:1.8.0_74]
	at java.util.ArrayList$SubList.get(ArrayList.java:1034) ~[na:1.8.0_74]
	at com.github.jknack.handlebars.Context.get(Context.java:590) ~[handlebars-4.0.5.jar:na]
	at com.github.jknack.handlebars.Context$BlockParam.get(Context.java:88) ~[handlebars-4.0.5.jar:na]
	at com.github.jknack.handlebars.internal.Variable.merge(Variable.java:171) ~[handlebars-4.0.5.jar:na]
```

Also doesn't work if you use `{{{..}}}`
However, it DOES work if you use `{{{../.}}}`!

**Comment by dontgitit** [comment]
Ah, think I found the issue. I think https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/Context.java#L83 should read 
```
      if (path.size() == 1 && (key.equals("this") || key.equals("."))) {
```

**Comment by dontgitit** [comment]
Hmm... actually it should resolve `this` context or the `parent` context to the `parent` context.

```
      if (path.size() == 1 && (key.equals("this") || key.equals(".") || key.equals("..")) {
```

**Comment by dontgitit** [comment]
thanks for the fix @jknack !
