### ISSUE TITLE
Exception while including helper.js

### ISSUE THREAD

**Issue by arvindbatra** [jknack/handlebars.java#604]
I am using Handlebars.java and when i pass my helpers.js, it throws the following exception

`
Bad language version: 180
java.lang.IllegalArgumentException: Bad language version: 180
	at org.mozilla.javascript.Context.checkLanguageVersion(Context.java:680)
	at org.mozilla.javascript.Context.setLanguageVersion(Context.java:648)
	at com.github.jknack.handlebars.internal.js.RhinoHandlebars.newContext(RhinoHandlebars.java:329)
	at com.github.jknack.handlebars.internal.js.RhinoHandlebars.registerHelpers(RhinoHandlebars.java:305)
	at com.github.jknack.handlebars.helper.DefaultHelperRegistry.registerHelpers(DefaultHelperRegistry.java:184)
	at com.github.jknack.handlebars.helper.DefaultHelperRegistry.registerHelpers(DefaultHelperRegistry.java:164)
`
My helper.js code is 
`Handlebars.registerHelper('hello2', function (context) {
 return 'Hello ' + context;
});`

Kindly suggest what I am doing wrong here?

**Comment by jknack** [comment]
probably bad (or new) javascript code. next release contains a Rhino upgrade, which in theory you can use ecma6
