### ISSUE TITLE
Literals such as "let", "const" not supported anymore in registerHelpers() API.

### ISSUE THREAD

**Issue by swjain** [jknack/handlebars.java#657]
To keep client and server side behavior consistent, we have this nice API to register helpers written in javascript, which was working absolutely fine until at least version 4.0.6.

Example helper.js file being loaded through [registerHelpers](https://github.com/jknack/handlebars.java/blob/master/handlebars/src/main/java/com/github/jknack/handlebars/Handlebars.java#L759) API:
```
helpers.and = function () {
    const len = arguments.length - 1;
    const options = arguments[len];
    let val = true;
    for (var i = 0; i < len; i++) {
        if (!arguments[i]) {
            val = false;
            break;
        }
    }
    return util.value(val, this, options);
};

Handlebars.registerHelper('and', helpers.and);
```
Getting this error on v4.1.0
```
Caused by: jdk.nashorn.internal.runtime.ParserException: <eval>:78:4 Expected an operand but found const
    const len = arguments.length - 1;
    ^
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:294)
	at jdk.nashorn.internal.parser.AbstractParser.error(AbstractParser.java:279)
	at jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:3182)
	at jdk.nashorn.internal.parser.Parser.expression(Parser.java:3282)
	at jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1150)
	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:967)
	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
	at jdk.nashorn.internal.parser.Parser.functionBody(Parser.java:2901)
	at jdk.nashorn.internal.parser.Parser.functionExpression(Parser.java:2663)
	at jdk.nashorn.internal.parser.Parser.memberExpression(Parser.java:2506)
	at jdk.nashorn.internal.parser.Parser.leftHandSideExpression(Parser.java:2372)
	at jdk.nashorn.internal.parser.Parser.unaryExpression(Parser.java:3147)
	at jdk.nashorn.internal.parser.Parser.expression(Parser.java:3325)
	at jdk.nashorn.internal.parser.Parser.expression(Parser.java:3282)
	at jdk.nashorn.internal.parser.Parser.expressionStatement(Parser.java:1150)
	at jdk.nashorn.internal.parser.Parser.statement(Parser.java:967)
	at jdk.nashorn.internal.parser.Parser.sourceElements(Parser.java:773)
	at jdk.nashorn.internal.parser.Parser.program(Parser.java:709)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:283)
	at jdk.nashorn.internal.parser.Parser.parse(Parser.java:249)
	at jdk.nashorn.internal.runtime.Context.compile(Context.java:1284)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:1251)
	at jdk.nashorn.internal.runtime.Context.compileScript(Context.java:627)
	at jdk.nashorn.api.scripting.NashornScriptEngine.compileImpl(NashornScriptEngine.java:535)
	... 26 more
```

**Note**: Though consuming scripts from lib area is a good practice but node 10 onwards the transpiled scripts themselves contains `let` or `const` literals and those aren't translated to `var`.
Hence, handlebars.java should continue allowing `let` and `const` while reading javacsipt source for helpers.

Or alternatively, we can always rewrite helpers sources to use `var` literal but `let` or `const` were already supported in earlier versions so why not in latest?
Also, the error message is not clear as to understand "what to fix?"

**Comment by jknack** [comment]
I'm afraid we can't do much here. It bc we replaced Rhino with Nashorn and now Nashorn doesn't support let/const expressions

**Comment by swjain** [comment]
Well, in that case, we can plug in an adapter to handle let/const while reading the script source. This will help your adopters to seamlessly load foreign helpers.
Let/const anyway is the thing of future and if we don't get this fixed, folks will either have to adapt themselves or they will not use your library.

**Comment by jknack** [comment]
yea, I know. Not sure if we can plug an adapter into Nashorn... but then Nashorn was removed from Java 9 (or probably 10)... so we need to find another alternative (don't like Rhino)

**Comment by swjain** [comment]
Hi @jknack,
Until we find an alternative, a basic adapter can still be plugged-in. Please check this PR: https://github.com/jknack/handlebars.java/pull/658
