### ISSUE TITLE
Partial call with line breaks between hash parameters cause exception since version 4.1.1

### ISSUE THREAD

**Issue by dudabone** [jknack/handlebars.java#660]
Since version 4.1.1, the following code causes exception:

```handlebars
text text text
{{#>some-partial param1="val1"
                 param2="val2"}}
    default content
{{/some-partial}}
```

This happens because there is a line break between param1 and param2. When reverting to <=4.1.0 or remove the line break everything works fine.

Exception is:

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is com.github.jknack.handlebars.HandlebarsException: classpath:/dist/resources/app/templates/template.hbs:3:17: found: 'param2', expected: '='
                 param2="val2"}}
                 ^
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:845)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1712)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
	at com.taboola.oauth.dataprovider.security.UserActiveFilter.doFilter(UserActiveFilter.java:57)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)

**Comment by jknack** [comment]
Side effect of https://github.com/jknack/handlebars.java/pull/658/commits/8edaf0b2aa2c71d3380cb95a6a8cfb9fbb121878

**Comment by jknack** [comment]
4.1.2 Released. Give central one hour or so.
