### ISSUE TITLE
Error parsing json field name starting with number

### ISSUE THREAD

**Issue by achigurupati** [jknack/handlebars.java#715]
String templateString = "Iam {{1lastname}}";
Handlebars handlebars = new Handlebars();
Template template = handlebars.compileInline(templateString);
String requestJSON = "{\"firstname\":\"John\", \"1lastname\":\"Doe\"}";
Object obj = new JsonSlurper().parseText(requestJSON);
String output = template.apply(obj);

when i execute this code, i get below exception. am using - com.github.jknack:handlebars:4.0.6 version.

com.github.jknack.handlebars.HandlebarsException: inline@62927a67:1:4: found: '{{', expected: '<EOF>'
Iam {{1lastname}}
    ^
	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:566)
	at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportInputMismatch(HbsErrorStrategy.java:186)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:148)
	at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:172)
	at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:84)
	at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:414)
	at com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:384)
	at com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:368)

**Comment by achigurupati** [comment]
never mind,...{{[1lastname]}} worked.
