### ISSUE TITLE
Can't register handlebars helpers in javascript file

### ISSUE THREAD

**Issue by a03771a** [jknack/handlebars.java#783]
My Java code is like this,
```
		TemplateLoader loader = new ClassPathTemplateLoader();
		handlebars = new Handlebars(loader);

		handlebars.registerHelpers("handlebar-helpers", this.getClass().getResourceAsStream("/handlebar-helpers.js"));
```
My handlebar-helpers.js is like this,
`
    /**
     * {{ debug }}
     */
    Handlebars.registerHelper("debug", function (optionalValue) {

        console.log("Current Context");
        console.log("====================");
        console.log(this);

    });

    /**
    * @param string default expects YYYYMMDD
    * @returns YYYY
    */
    Handlebars.registerHelper('year', function (val, object, start, end) {

        let _start = object.hash.start ? object.hash.start : (start?0:start);
        let _end = object.hash.end ? object.hash.end : (end?4:end);
        let rtn = val.trim().substring(_start, _end);

        return new Handlebars.SafeString(rtn);
    });
`
I use hanlebars.java version 4.2.0 and the error message is like this,
`
Caused by: java.lang.ClassCastException: Cannot cast jdk.nashorn.internal.runtime.ScriptFunction to com.github.jknack.handlebars.Helper
	at java.lang.invoke.MethodHandleImpl.newClassCastException(MethodHandleImpl.java:361) [rt.jar:1.8.0_241]
	at java.lang.invoke.MethodHandleImpl.castReference(MethodHandleImpl.java:356) [rt.jar:1.8.0_241]
	at jdk.nashorn.internal.scripts.Script$Recompilation$12$625AA$\^eval\_.registerHelper(<eval>:48)
	at jdk.nashorn.internal.scripts.Script$11$\^eval\_.:program(<eval>:5)
	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
...
`

**Comment by a03771a** [comment]
[helpers.nashorn.js.zip](https://github.com/jknack/handlebars.java/files/4674757/helpers.nashorn.js.zip)
I have successfully fixed this issue, please use attached helpers.nashorn.js and re-package it into the jar.
