### ISSUE TITLE
Support Java 15

### ISSUE THREAD

**Issue by mohamnag** [jknack/handlebars.java#808]
I wonder why I'm the only/first one raising this issue when Java 15 has already been released for a while.
Running on OpenJDK 15, when trying to load JavaScript files as per `handlebars.registerHelpers(jsFile)` an NPE with following stack happens:

```
java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.put(String, Object)" because "this.engine" is null
	at com.github.jknack.handlebars.helper.DefaultHelperRegistry.engine(DefaultHelperRegistry.java:303)
	at com.github.jknack.handlebars.helper.DefaultHelperRegistry.registerHelpers(DefaultHelperRegistry.java:193)
	at com.github.jknack.handlebars.helper.DefaultHelperRegistry.registerHelpers(DefaultHelperRegistry.java:173)
	at com.github.jknack.handlebars.Handlebars.registerHelpers(Handlebars.java:688)
```

which is pointing at around this line:

```java
        this.engine = new ScriptEngineManager().getEngineByName("nashorn");

        this.engine.put("Handlebars_java", this);
```

the problem is trying to load *nashorn* which is not anymore bundled/supported as of Java 15. 
Has there been any experiments switching to *graal.js*?  are there/will be other problems with Java 15? Why I don't find any hints or comments about handlebars usage with Java 15?

**Comment by forzatos** [comment]
A bit to late maybe... I had the same issues since nashorn is not bundled anymore.
Did some  "hacking" and managed to get GraalJS to work as the engine for the script engine manager.
