### ISSUE TITLE
Syntax error when single quote is present.

### ISSUE THREAD

**Issue by HugoMario** [jknack/handlebars.java#946]
I'm trying to generate docs from templates but when a single quote ( `'` ) is used an exception is thrown when a template is being compiled. For example:

```php
### Example
```php
<?php
require_once(__DIR__ . '/vendor/autoload.php');
{{#hasAuthMethods}}{{#authMethods}}{{#isBasic}}
// Configure HTTP basic authorization: {{{name}}}
$config = {{{invokerPackage}}}\Configuration::getDefaultConfiguration()
              ->setUsername('YOUR_USERNAME')
              ->setPassword('YOUR_PASSWORD');
```
Full template file [here](https://github.com/swagger-api/swagger-codegen-generators/blob/master/src/main/resources/handlebars/php/api_doc.mustache): 

The error i got is:
```cmd
Caused by: com.github.jknack.handlebars.HandlebarsException: /handlebars/php/api_doc.mustache:24:24: found: '/vendor/autoload.php'', expected: '}}'
require_once(__DIR__ . '/vendor/autoload.php');
                        ^
	at com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at com.github.jknack.handlebars.internal.antlr.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at com.github.jknack.handlebars.internal.antlr.Parser.notifyErrorListeners(Parser.java:544)
	at com.github.jknack.handlebars.internal.HbsErrorStrategy.reportInputMismatch(HbsErrorStrategy.java:186)
	at com.github.jknack.handlebars.internal.antlr.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
	at com.github.jknack.handlebars.internal.HbsParser.var(HbsParser.java:1293)
	at com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:333)
	at com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:231)
	at com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:174)
	at com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:86)
	at com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:513)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:438)
	at com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:419)

```

replacing single quote ( `'` ) by double quote ( `"` ) avoid getting the exception on compiled.

I got this on version `4.2.1` and `4.3.0`. However in `4.1.2` the issue is not present.

**Comment by HugoMario** [comment]
The error is actually because the sentence:

```
{{concat invokerPackage '\\' classname}}{{#description}}
```

located on top of template file. however this error does not happen in `4.1.2` version. Going to close this and open a new more accurated issue.
